version: '3.8'
services:
  redis:
    image: redis
    container_name: movietest-redis
    ports:
      - "6379:6379"
    networks:
      - my_network
  movietest-movieinfo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movietest-movieinfo
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my_network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network: