global:
  scrape_interval: 5s  # Adjust as needed

scrape_configs:
  - job_name: 'movietest-movieinfo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['movietest-movieinfo:8080']